### ISSUE TITLE
Adicionar Felipe Torres na grade do site

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#17]
* **Nome:** Felipe Torres
*  **Mini-bio:** Entusiasta em bancos de dados aplicados a dados médicos, ama programação em Python, análises de dados em JAVA, plotar gráficos em R e fazer páginas web em PHP com Code Igniter. Ele é motivado por desafios e nas horas vagas nunca nega uma roda de capoeira ao toque do berimbau. Obteve o título de bacharel em Sistemas de Informação pela UNIJORGE e Mestre em computação aplicada a saúde pela UEFS. Atualmente, faz doutorado em Biotecnologia na FIOCRUZ, atuando em
diversos projetos de computação aplicada a saúde.
* **linkedin**: https://www.linkedin.com/mynetwork/
* **github**: github.com/fgtorres
* **foto**: https://scontent.fcgh7-1.fna.fbcdn.net/v/t1.0-1/15726262_1807446559505104_3357511279356336903_n.jpg?oh=ba54e7f5b025bcd1efbe7ca04b2e688f&oe=5901AB20

## Atividade

* **Palestra:** Desafios de trabalhar com dados médicos no Brasil
* **Descrição:** O objetivo desta palestra é falar um pouco sobre a área de ciência de dados médicos. 
Suas dificuldades; principais arquiteturas de armazenamento e análise de dados atuais; 
Como as comunidades open-sources tem apoiado os avanços médicos atuais ? Integração comunidades e ciência.
* **Dia:** Sábado
* **Horário:** 14:00 - 14:50

**Comment by mmalaquias1** [comment]
Feito
