### ISSUE TITLE
Adicionar Lucas Nascimento na grade do site

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#18]
* **Nome:** Lucas Nascimento
*  **Mini-bio:** Lucas Nascimento Santos (@ll_ucasn), engenheiro de software. Estudante de Ciência da Computação na Universidade Salvador (UNIFACS). Possui habilidades em websites e sistemas sobre demandas há mais de 6 anos. Atualmente atua como engenheiro de software de dispositivos mobile híbridos, mineração de dados e com projetos freelances. Integrante do Diretório Acadêmico de Ciência da Computação (DACC) e do grupo de pesquisa da UNIFACS GPTI (Grupo de Pesquisa da Tecnologia da Informação). Tenho interesses nas áreas de aprendizado de máquina, ciência de dados e mineração de dados no qual participo do grupo de pesquisa. Atletas nas horas vagas e apaixonado por aprender, sobre novas tecnologia e tendenciais no mundo da computação.

* **linkedin**: 
* **github**: 
* **foto**: 
## Atividade

* **Palestra:** Redis: Escalando sua aplicação para suportar milhões
* **Descrição:** Irei apresentar umas das ferramentas mais importantes atuamente no mercado para se conseguir o máximo de escalabilidade e disponibilidade em sua aplicação que você pode oferecer ao seu usuário final.
* **Dia:** Sexta
* **Horário:** 15:00 - 15:50

**Comment by mmalaquias1** [comment]
Feito
