### ISSUE TITLE
Adicionar na grade Ivo Marcelo Leonardi Zaniolo

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#21]
* **Nome:** Ivo Marcelo Leonardi Zaniolo
*  **Mini-bio:** Marcelo, surfista, empreendedor por natureza, CTO da Onyx Labs e principalmente
apaixonado por programação.
Há doze anos no mercado brasileiro não se contenta com uma linguagem ou plataforma, 
rejeita a dualidade prevalente no mercado e acredita na filosofia Open-Source tanto 
para o desenvolvimento de software quanto para a disseminação de conhecimento.
Atualmente direciona tecnologicamente algumas startups baianas com potencial 
de crescimento exponencial.

* **twitter**: https://twitter.com/imarcelolz
* **linkedin**: https://www.linkedin.com/in/imarcelolz/?locale=pt_BR
* **github**: https://github.com/imarcelolz
* **foto**: Em anexo
## Atividade

* **Palestra:** Brincando com NoSql
* **Descrição:** Breve apresentação sobre uma experiência de implantação do maior cluster brasileiro de Cassandra no ano de 2011. 
Este foi projeto de vanguardista que aconteceu em Curitiba em uma das startups do Grupo Buscapé chamaad e-Behaviour.

Temas que pretendo abordar:
1. Porque efetuamos a mudança para NoSql;
2. Quais as dificuldades e problemas encontrados durante a migração;
3. Pós Implantação, como processar 10gb de informações por dia, extrair conhecimento;

* **Dia:** Sábado
* **Horário:** 15:00 - 15:50

__

* **Mini-curso:** Workshop Rails 5 + MongoDb
* **Descrição:** Neste workshop Marcelo apresentará como realizar a integração
do Rails 5.0 com o banco de dados MongoDB, de forma simples e intuitiva.
Além disso, demonstrará porque este framework, com 11 anos de idade,
continua sendo uma excelente opção para a criação de pequenos e grandes projetos
de forma rápida, robusta e eficiente.
* **softwares necessários**:

1. [Virtualbox](https://www.virtualbox.org/wiki/Downloads)
1. [Vagrant](https://www.vagrantup.com/)
1. [atom](https://atom.io/)

* **Dia:** Quinta-feira
* **Horário:** Manhã

**Comment by otaviojava** [comment]
![redes-sociais](https://cloud.githubusercontent.com/assets/863011/22499193/647a29f6-e844-11e6-90b5-040fb584e955.jpg)

**Comment by mmalaquias1** [comment]
feito
