### ISSUE TITLE
Adicionar na grade Ivan Queiroz

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#22]
* **Nome:** Ivan Queiroz
*  **Mini-bio:** Bacharel em Sistemas de Informação pela Estácio de Sá / FIB
Analista de Sistemas a nove anos. Atualmente na Indra Brasil na área de clientes de Telecom.
Principal cliente atual é a Vivo, em sistemas ligados as áreas de atendimento ao cliente (CRM), vendas e jurídica. Experiência em Java, C++ e PHP; desenvolvendo sistemas desktop, web e middleware.

* **twitter**: 
* **linkedin**: 
* **github**: 
* **foto**: 
## Atividade

* **Palestra:** Spring Data MongoDB - visão geral do framework
* **Descrição:** Uma apresentação sobre o spring data e spring data mongodb mostrando as características, facilidades, vantagens e desvantagens. Uma visão geral, apresentando o framework para o público.

* **Dia:** Sábado
* **Horário:** 11:00 - 12:00

__

* **Mini-curso:** Spring data neo4j com spring boot
* **Descrição:** O mini-curso trará uma introdução sobre o uso do banco não relacional orientado a grafo neo4j usando spring data e spring boot.
* **Dia:** Quinta-feira
* **Horário:** Manhã

**Comment by mmalaquias1** [comment]
feito
