### ISSUE TITLE
Adicionar informações do Andrew Medina

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#29]
* **Nome:** Andrews Medina
*  **Mini-bio:** Desenvolvedor na JusBrasil, um dos fundadores do tsuru, uso Go desde 2012. Trabalho com automação de infra estrutura, garantindo a escalabilidade e disponibilidade das aplicações.

* **twitter**: https://twitter.com/andrewsmedina
* **linkedin**: https://www.linkedin.com/in/andrewsmedina
* **github**: https://github.com/andrewsmedina
* **foto**: Em anexo

**Comment by otaviojava** [comment]
![medina](https://cloud.githubusercontent.com/assets/863011/22668421/d71f9c54-eca7-11e6-9d38-31ba3a3550f2.jpg)

**Comment by mmalaquias1** [comment]
Feioto? ?!
