### ISSUE TITLE
Adicionar Julio M Faerman como palestrante da Amazon

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#3]
* **Atividade**: Palestra
* **Título**:  NoSQL na AWS com DynamoDB
* **Descrição**:  O Amazon DynamoDB é um serviço de banco de dados NoSQL rápido e flexível para todas as aplicações que precisam de latência constante: abaixo de 10 milissegundos em qualquer escala. O serviço é um banco de dados em nuvem totalmente gerenciado e é compatível com os modelos de armazenamento de documentos e de chave-valor. Seu modelo de dados flexível e desempenho previsível o tornam muito adequado para aplicativos móveis e web, jogos, tecnologias de anúncios, IoT e muitas outras aplicações.
Esta é uma apresentação para desenvolvedores que mostra os principais conceitos, técnicas e otimizações para se programar utilizando as APIs do Amazon DynamoDB e extrair o maior benefício de sua capacidade. Exploremos como projetar índices e consultas para sua aplicação, assim como as funcionalidades mais importantes, como suporte à JSON, Streams e integrações. Venha conhecer o banco de dados por trás de casos de alta escala como BMW, Duolingo e Supercell.

_______

* **Atividade**: Mini-curso
* **Título**: Conhecendo o Dynamodb
* **Descrição**:   Amazon DynamoDB é um serviço de banco de dados NoSQL rápido e flexível para todas as aplicações que precisam de latência constante: abaixo de 10 milissegundos em qualquer escala. O serviço é um banco de dados em nuvem totalmente gerenciado e é compatível com os modelos de armazenamento de documentos e de chave-valor. Seu modelo de dados flexível e desempenho previsível o tornam muito adequado para aplicativos móveis e web, jogos, tecnologias de anúncios, IoT e muitas outras aplicações.
Neste workshop vamos explorar o dynamodb em laboratórios práticos e sem custo adicional. Serão fornecidas contas da AWS, orientação passo-a-passo e mentoria para desenvolver experiência concreta com o serviço. Venha experimentar na prática o banco de dados por trás de casos de alta escala como BMW, Duolingo e Supercell.
_______

* **Nome**: Julio M Faerman
* **Mini-bio**: Julio é engenheiro de software e educador, fascinado em entender como e porquê aprendemos. Na Amazon Web Services é responsável pelo relacionamento com desenvolvedores, levando as novidades da computação em nuvem e trazendo as experiências de quem a utiliza. Também é fundador da Craftware, uma startup para inovação em educação. Antes disso, trabalhou na Red Hat, na Borland e em grandes organizações de governo e telecom.
Link:  http://www.thedevelopersconference.com.br/img/fotos/julio-faerman.jpg;jsessionid=E3231D72A08BC9EDB59C2DB0DECE6DA1

**Comment by mmalaquias1** [comment]
Feito

**Comment by otaviojava** [comment]
@mmalaquias1 uma vez que a grade está pronto, talvez já colocar as atividades do Julio.

**Comment by mmalaquias1** [comment]
adicionado na grade :)
