### ISSUE TITLE
Adicionar na grade Lucas Humenhuk

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#30]
* **Nome:** Lucas Humenhuk
*  **Mini-bio:** Lucas Humenhuk é Technical Evangelist na Microsoft há pouco mais de 2 anos. Geek, é viciado em música e séries, AI e BigData,.

* **twitter**: https://twitter.com/mslucash
* **linkedin**: https://www.linkedin.com/in/mslucash
* **github**: https://github.com/lcarli
* **foto**: https://1drv.ms/i/s!AkInlHYUNYMLhcFCFqO90J7ogrrnnw
## Atividade

* **Palestra:** No-SQL no Azure
* **Descrição:** Venha conhecer os bancos de dados não relacionais que a Microsoft dispõe em sua nuvem e algumas dicas sobre como tirar proveito deste universo.

* **Dia:** Sexta-feira
* **Horário:** 14:00 - 14:50

**Comment by mmalaquias1** [comment]
Foi feito. ?!
