### ISSUE TITLE
Deixar espaço para link de inscrição

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/nosqlba#4]
Deixa em um ou mais locais o link para inscrição do evento.

http://inscricao.nosqlba.org/

p.s: Tão logo o domínio seja confirmado mudaremos para inscricao.nosqlba.org

**Comment by mmalaquias1** [comment]
Pull request feito.

**Comment by otaviojava** [comment]
@mmalaquias1 ,por favor, tirar a logo do JNoSQL, lembrando o evento do JavaBAhia. Podemos falar do JNOSQL, mas que está promovendo esse evento é o JavaBahia.
